"""Parte 5: configuración de la cooperativa, lugares, correlativos, tandas, decisiones sobre la tanda y DOP.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05

Regla: toda tabla nueva lleva ALTER TABLE <tabla> ENABLE ROW LEVEL SECURITY y ninguna política.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

TABLAS = ("configuracion_cooperativa", "lugares", "correlativos", "tandas", "decisiones_tanda", "dops")
ENTIDADES_ANTES = "'productor', 'parcela', 'visita', 'analisis'"
ENTIDADES_AHORA = ENTIDADES_ANTES + ", 'tanda', 'dop'"
TIPOS_ANTES = (
    "'dni', 'constancia_ppa', 'sustento_midagri', 'archivo_geometria', 'titulo_sunarp', 'constancia_posesion', "
    "'cusaf', 'autorizacion_serfor', 'sunafil', 'sunat', 'zonificacion', 'foto_visita', 'respuesta_analisis'"
)
TIPOS_AHORA = TIPOS_ANTES + ", 'guia_remision', 'dop_pdf'"
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | Sequence[str] | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_cooperativa',
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('tope_kg_seco_ha_anio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('factor_baba_a_seco', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.390'), nullable=False),
    sa.Column('rendimiento_min', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.330'), nullable=False),
    sa.Column('rendimiento_max', sa.Numeric(precision=4, scale=3), server_default=sa.text('0.450'), nullable=False),
    sa.Column('dias_max_cosecha_entrega_baba', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('dias_max_cosecha_entrega_seco', sa.Integer(), server_default=sa.text('90'), nullable=False),
    sa.Column('tolerancia_peso_guia_pct', sa.Numeric(precision=4, scale=1), server_default=sa.text('5.0'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dias_max_cosecha_entrega_baba >= 0 AND dias_max_cosecha_entrega_seco >= 0', name=op.f('ck_configuracion_cooperativa_dias_no_negativos')),
    sa.CheckConstraint('factor_baba_a_seco > 0 AND factor_baba_a_seco < 1', name=op.f('ck_configuracion_cooperativa_factor_entre_0_y_1')),
    sa.CheckConstraint('rendimiento_min > 0 AND rendimiento_min < rendimiento_max AND rendimiento_max < 1', name=op.f('ck_configuracion_cooperativa_banda_rendimiento_valida')),
    sa.CheckConstraint('tolerancia_peso_guia_pct >= 0', name=op.f('ck_configuracion_cooperativa_tolerancia_no_negativa')),
    sa.CheckConstraint('tope_kg_seco_ha_anio IS NULL OR tope_kg_seco_ha_anio > 0', name=op.f('ck_configuracion_cooperativa_tope_positivo')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_configuracion_cooperativa_cooperativa_id_cooperativas')),
    sa.PrimaryKeyConstraint('cooperativa_id', name=op.f('pk_configuracion_cooperativa'))
    )
    op.create_table('correlativos',
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('ultimo', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('tanda', 'dop')", name=op.f('ck_correlativos_tipo_valido')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_correlativos_cooperativa_id_cooperativas')),
    sa.PrimaryKeyConstraint('cooperativa_id', 'tipo', 'anio', name=op.f('pk_correlativos'))
    )
    op.create_table('lugares',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('departamento', sa.Text(), nullable=False),
    sa.Column('provincia', sa.Text(), nullable=False),
    sa.Column('distrito', sa.Text(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('cancha_acopio', 'planta', 'almacen', 'otro')", name=op.f('ck_lugares_tipo_valido')),
    sa.CheckConstraint('latitud IS NULL OR latitud BETWEEN -90 AND 90', name=op.f('ck_lugares_latitud_valida')),
    sa.CheckConstraint('longitud IS NULL OR longitud BETWEEN -180 AND 180', name=op.f('ck_lugares_longitud_valida')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_lugares_cooperativa_id_cooperativas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lugares')),
    sa.UniqueConstraint('cooperativa_id', 'nombre', name='uq_lugares_cooperativa_nombre')
    )
    op.create_table('tandas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('productor_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=False),
    sa.Column('lugar_id', sa.UUID(), nullable=False),
    sa.Column('recibida_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado_producto', sa.Text(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('numero_sacos', sa.Integer(), nullable=True),
    sa.Column('humedad_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('variedad', sa.Text(), nullable=False),
    sa.Column('variedad_otra', sa.Text(), nullable=True),
    sa.Column('tipo_semilla', sa.Text(), nullable=True),
    sa.Column('cosecha_desde', sa.Date(), nullable=False),
    sa.Column('cosecha_hasta', sa.Date(), nullable=False),
    sa.Column('gre_numero', sa.Text(), nullable=True),
    sa.Column('gre_fecha_emision', sa.Date(), nullable=True),
    sa.Column('gre_ruc_emisor', sa.String(length=11), nullable=True),
    sa.Column('gre_peso_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Text(), server_default='registrada', nullable=False),
    sa.Column('registrada_por', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(variedad = 'otra') = (variedad_otra IS NOT NULL)", name=op.f('ck_tandas_variedad_otra_si_otra')),
    sa.CheckConstraint("estado IN ('registrada', 'observada', 'validada', 'anulada')", name=op.f('ck_tandas_estado_valido')),
    sa.CheckConstraint("estado_producto IN ('baba', 'seco')", name=op.f('ck_tandas_estado_producto_valido')),
    sa.CheckConstraint("gre_ruc_emisor IS NULL OR gre_ruc_emisor ~ '^[0-9]{11}$'", name=op.f('ck_tandas_gre_ruc_11_digitos')),
    sa.CheckConstraint("humedad_pct IS NULL OR (estado_producto = 'seco' AND humedad_pct BETWEEN 0 AND 100)", name=op.f('ck_tandas_humedad_solo_en_seco')),
    sa.CheckConstraint('cosecha_desde <= cosecha_hasta', name=op.f('ck_tandas_cosecha_ordenada')),
    sa.CheckConstraint('gre_peso_kg IS NULL OR gre_peso_kg > 0', name=op.f('ck_tandas_gre_peso_positivo')),
    sa.CheckConstraint('numero_sacos IS NULL OR numero_sacos > 0', name=op.f('ck_tandas_sacos_positivos')),
    sa.CheckConstraint('peso_kg > 0', name=op.f('ck_tandas_peso_positivo')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_tandas_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugares.id'], name=op.f('fk_tandas_lugar_id_lugares')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name=op.f('fk_tandas_parcela_id_parcelas')),
    sa.ForeignKeyConstraint(['productor_id'], ['productores.id'], name=op.f('fk_tandas_productor_id_productores')),
    sa.ForeignKeyConstraint(['registrada_por'], ['perfiles.id'], name=op.f('fk_tandas_registrada_por_perfiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tandas')),
    sa.UniqueConstraint('cooperativa_id', 'codigo', name='uq_tandas_cooperativa_codigo')
    )
    op.create_index('ix_tandas_guia', 'tandas', ['gre_ruc_emisor', 'gre_numero'], unique=False)
    op.create_index('ix_tandas_parcela_recibida', 'tandas', ['parcela_id', 'recibida_en'], unique=False)
    op.create_table('decisiones_tanda',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tanda_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('decidida_por', sa.UUID(), nullable=False),
    sa.Column('decidida_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('requisitos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("decision IN ('validar', 'observar', 'anular')", name=op.f('ck_decisiones_tanda_decision_valida')),
    sa.ForeignKeyConstraint(['decidida_por'], ['perfiles.id'], name=op.f('fk_decisiones_tanda_decidida_por_perfiles')),
    sa.ForeignKeyConstraint(['tanda_id'], ['tandas.id'], name=op.f('fk_decisiones_tanda_tanda_id_tandas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisiones_tanda'))
    )
    op.create_index('ix_decisiones_tanda_tanda', 'decisiones_tanda', ['tanda_id', 'decidida_en'], unique=False)
    op.create_table('dops',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('tanda_id', sa.UUID(), nullable=False),
    sa.Column('productor_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=False),
    sa.Column('emitido_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emitido_por', sa.UUID(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contenido_sha256', sa.String(length=64), nullable=False),
    sa.Column('pdf_documento_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Text(), server_default='vigente', nullable=False),
    sa.Column('anulado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_por', sa.UUID(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.CheckConstraint("(estado = 'anulado') = (anulado_en IS NOT NULL AND anulado_por IS NOT NULL AND motivo_anulacion IS NOT NULL)", name=op.f('ck_dops_anulacion_completa')),
    sa.CheckConstraint("contenido_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_dops_sha256_hex')),
    sa.CheckConstraint("estado IN ('vigente', 'anulado')", name=op.f('ck_dops_estado_valido')),
    sa.ForeignKeyConstraint(['anulado_por'], ['perfiles.id'], name=op.f('fk_dops_anulado_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_dops_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['emitido_por'], ['perfiles.id'], name=op.f('fk_dops_emitido_por_perfiles')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name=op.f('fk_dops_parcela_id_parcelas')),
    sa.ForeignKeyConstraint(['pdf_documento_id'], ['documentos.id'], name=op.f('fk_dops_pdf_documento_id_documentos')),
    sa.ForeignKeyConstraint(['productor_id'], ['productores.id'], name=op.f('fk_dops_productor_id_productores')),
    sa.ForeignKeyConstraint(['tanda_id'], ['tandas.id'], name=op.f('fk_dops_tanda_id_tandas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dops')),
    sa.UniqueConstraint('codigo', name=op.f('uq_dops_codigo')),
    sa.UniqueConstraint('tanda_id', name=op.f('uq_dops_tanda_id'))
    )
    op.create_index('ix_dops_cooperativa_emitido', 'dops', ['cooperativa_id', 'emitido_en'], unique=False)
    op.add_column('cooperativas', sa.Column('codigo', sa.String(length=6), nullable=True))
    op.create_unique_constraint(op.f('uq_cooperativas_codigo'), 'cooperativas', ['codigo'])
    # ### end Alembic commands ###

    # ---------- cooperativas: código de 3 a 6 letras ----------
    op.create_check_constraint(
        op.f("ck_cooperativas_codigo_3_a_6_letras"), "cooperativas", "codigo IS NULL OR codigo ~ '^[A-Z]{3,6}$'"
    )

    # ---------- documentos: guía de remisión y PDF del DOP ----------
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_AHORA})")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_AHORA})")

    # ---------- decisiones_tanda: no se editan ni se borran ----------
    op.execute(
        """
        CREATE FUNCTION decisiones_tanda_inmutables() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Las decisiones sobre una tanda no se editan ni se borran';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER tg_decisiones_tanda_inmutables BEFORE UPDATE OR DELETE ON decisiones_tanda "
        "FOR EACH ROW EXECUTE FUNCTION decisiones_tanda_inmutables()"
    )

    # ---------- dops: el sello no cambia y el DOP no se borra ----------
    op.execute(
        """
        CREATE FUNCTION dops_sellados() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'Un DOP no se borra: se anula';
            END IF;
            IF NEW.contenido IS DISTINCT FROM OLD.contenido
               OR NEW.contenido_sha256 IS DISTINCT FROM OLD.contenido_sha256
               OR NEW.codigo IS DISTINCT FROM OLD.codigo
               OR NEW.tanda_id IS DISTINCT FROM OLD.tanda_id THEN
                RAISE EXCEPTION 'El contenido sellado de un DOP no cambia';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER tg_dops_sellados BEFORE UPDATE OR DELETE ON dops "
        "FOR EACH ROW EXECUTE FUNCTION dops_sellados()"
    )

    for tabla in TABLAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY")



def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS tg_dops_sellados ON dops")
    op.execute("DROP FUNCTION IF EXISTS dops_sellados()")
    op.execute("DROP TRIGGER IF EXISTS tg_decisiones_tanda_inmutables ON decisiones_tanda")
    op.execute("DROP FUNCTION IF EXISTS decisiones_tanda_inmutables()")
    op.execute("DELETE FROM documentos WHERE entidad IN ('tanda', 'dop')")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_ANTES})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_ANTES})")
    op.drop_constraint(op.f("ck_cooperativas_codigo_3_a_6_letras"), "cooperativas", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_cooperativas_codigo'), 'cooperativas', type_='unique')
    op.drop_column('cooperativas', 'codigo')
    op.drop_index('ix_dops_cooperativa_emitido', table_name='dops')
    op.drop_table('dops')
    op.drop_index('ix_decisiones_tanda_tanda', table_name='decisiones_tanda')
    op.drop_table('decisiones_tanda')
    op.drop_index('ix_tandas_parcela_recibida', table_name='tandas')
    op.drop_index('ix_tandas_guia', table_name='tandas')
    op.drop_table('tandas')
    op.drop_table('lugares')
    op.drop_table('correlativos')
    op.drop_table('configuracion_cooperativa')
    # ### end Alembic commands ###
