"""Adenda 2 de la Parte 4: imagenes satelitales y revisiones de imagenes

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 22:01:31.779569

Regla: toda tabla nueva lleva ALTER TABLE <tabla> ENABLE ROW LEVEL SECURITY y ninguna política.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | Sequence[str] | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLAS = ("imagenes_parcela", "revisiones_imagenes", "consumo_imagenes")
ENTIDADES_ANTES = "'productor', 'parcela', 'visita', 'analisis', 'tanda', 'dop'"
ENTIDADES_AHORA = ENTIDADES_ANTES + ", 'imagen'"
TIPOS_ANTES = (
    "'dni', 'constancia_ppa', 'sustento_midagri', 'archivo_geometria', 'titulo_sunarp', 'constancia_posesion', "
    "'cusaf', 'autorizacion_serfor', 'sunafil', 'sunat', 'zonificacion', 'foto_visita', 'respuesta_analisis', "
    "'guia_remision', 'dop_pdf'"
)
TIPOS_AHORA = TIPOS_ANTES + ", 'imagen_satelital', 'imagen_externa'"
SISTEMA_ANTES = "subido_por IS NOT NULL OR tipo = 'respuesta_analisis'"
SISTEMA_AHORA = "subido_por IS NOT NULL OR tipo IN ('respuesta_analisis', 'imagen_satelital')"

# Una revisión de imágenes no se edita ni se borra: solo se anula una vez, con motivo.
FUNCION_REVISIONES = """
CREATE FUNCTION revisiones_imagenes_inmutables() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Una revisión de imágenes no se borra: se anula con motivo.';
    END IF;
    IF OLD.anulada_en IS NOT NULL
       OR NEW.parcela_id IS DISTINCT FROM OLD.parcela_id
       OR NEW.cooperativa_id IS DISTINCT FROM OLD.cooperativa_id
       OR NEW.revisada_por IS DISTINCT FROM OLD.revisada_por
       OR NEW.revisada_en IS DISTINCT FROM OLD.revisada_en
       OR NEW.imagenes IS DISTINCT FROM OLD.imagenes
       OR NEW.observacion_2020 IS DISTINCT FROM OLD.observacion_2020
       OR NEW.observacion_cambio IS DISTINCT FROM OLD.observacion_cambio
       OR NEW.descripcion IS DISTINCT FROM OLD.descripcion
       OR NEW.geometria_sha256 IS DISTINCT FROM OLD.geometria_sha256 THEN
        RAISE EXCEPTION 'Una revisión de imágenes no se edita: se anula con motivo y se registra otra.';
    END IF;
    RETURN NEW;
END;
$$;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_imagenes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mes', sa.Date(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('pu', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('peticiones', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pu >= 0', name=op.f('ck_consumo_imagenes_pu_no_negativas')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_consumo_imagenes_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name=op.f('fk_consumo_imagenes_parcela_id_parcelas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumo_imagenes'))
    )
    op.create_index('ix_consumo_imagenes_mes', 'consumo_imagenes', ['mes'], unique=False)
    op.create_table('imagenes_parcela',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('fuente', sa.Text(), nullable=False),
    sa.Column('papel', sa.Text(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('fecha_captura', sa.Date(), nullable=True),
    sa.Column('dias_respecto_al_corte', sa.Integer(), nullable=True),
    sa.Column('resolucion_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('nubes_parcela_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('identificador_fuente', sa.Text(), nullable=True),
    sa.Column('proveedor', sa.Text(), nullable=True),
    sa.Column('geometria_sha256', sa.String(length=64), nullable=False),
    sa.Column('documento_natural_id', sa.UUID(), nullable=True),
    sa.Column('documento_infrarrojo_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Text(), server_default='pendiente', nullable=False),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('reemplazada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargada_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado <> 'generada' OR fecha_captura IS NOT NULL", name=op.f('ck_imagenes_parcela_generada_con_fecha')),
    sa.CheckConstraint("estado IN ('pendiente', 'generada', 'sin_imagen_utilizable', 'error')", name=op.f('ck_imagenes_parcela_estado_valido')),
    sa.CheckConstraint("fuente IN ('sentinel2', 'esri_wayback', 'externa')", name=op.f('ck_imagenes_parcela_fuente_valida')),
    sa.CheckConstraint("geometria_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_imagenes_parcela_sha256_hex')),
    sa.CheckConstraint("papel IN ('anterior_al_corte', 'anual', 'reciente', 'alta_resolucion', 'externa')", name=op.f('ck_imagenes_parcela_papel_valido')),
    sa.CheckConstraint('nubes_parcela_pct IS NULL OR nubes_parcela_pct BETWEEN 0 AND 100', name=op.f('ck_imagenes_parcela_nubes_porcentaje')),
    sa.ForeignKeyConstraint(['cargada_por'], ['perfiles.id'], name=op.f('fk_imagenes_parcela_cargada_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_imagenes_parcela_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['documento_infrarrojo_id'], ['documentos.id'], name=op.f('fk_imagenes_parcela_documento_infrarrojo_id_documentos')),
    sa.ForeignKeyConstraint(['documento_natural_id'], ['documentos.id'], name=op.f('fk_imagenes_parcela_documento_natural_id_documentos')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name=op.f('fk_imagenes_parcela_parcela_id_parcelas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imagenes_parcela'))
    )
    op.create_index('ix_imagenes_parcela_cola', 'imagenes_parcela', ['estado', 'creado_en'], unique=False)
    op.create_index('ix_imagenes_parcela_parcela', 'imagenes_parcela', ['parcela_id', 'geometria_sha256'], unique=False)
    op.create_table('revisiones_imagenes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('revisada_por', sa.UUID(), nullable=False),
    sa.Column('revisada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('imagenes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observacion_2020', sa.Text(), nullable=False),
    sa.Column('observacion_cambio', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('geometria_sha256', sa.String(length=64), nullable=False),
    sa.Column('anulada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_por', sa.UUID(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("geometria_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_revisiones_imagenes_sha256_hex')),
    sa.CheckConstraint("observacion_2020 IN ('bosque', 'cultivo_o_uso_agricola', 'mixto', 'no_se_distingue')", name=op.f('ck_revisiones_imagenes_observacion_2020_valida')),
    sa.CheckConstraint("observacion_cambio IN ('sin_cambio_visible', 'cambio_visible', 'no_se_distingue')", name=op.f('ck_revisiones_imagenes_observacion_cambio_valida')),
    sa.CheckConstraint('(anulada_en IS NULL) = (anulada_por IS NULL AND motivo_anulacion IS NULL)', name=op.f('ck_revisiones_imagenes_anulacion_completa')),
    sa.CheckConstraint('char_length(descripcion) >= 50', name=op.f('ck_revisiones_imagenes_descripcion_minima')),
    sa.ForeignKeyConstraint(['anulada_por'], ['perfiles.id'], name=op.f('fk_revisiones_imagenes_anulada_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_revisiones_imagenes_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], name=op.f('fk_revisiones_imagenes_parcela_id_parcelas')),
    sa.ForeignKeyConstraint(['revisada_por'], ['perfiles.id'], name=op.f('fk_revisiones_imagenes_revisada_por_perfiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisiones_imagenes'))
    )
    op.create_index('ix_revisiones_imagenes_parcela', 'revisiones_imagenes', ['parcela_id', 'revisada_en'], unique=False)
    op.add_column('decisiones_habilitacion', sa.Column('evidencia_revision_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_decisiones_habilitacion_evidencia_revision_id_revisiones_imagenes'), 'decisiones_habilitacion', 'revisiones_imagenes', ['evidencia_revision_id'], ['id'])
    # ### end Alembic commands ###

    # Documentos: las imágenes son documentos generados por el sistema (o cargados, si son externas).
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_AHORA})")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_AHORA})")
    op.drop_constraint(op.f("ck_documentos_subido_por_si_no_sistema"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_subido_por_si_no_sistema"), "documentos", SISTEMA_AHORA)

    op.execute(FUNCION_REVISIONES)
    op.execute(
        "CREATE TRIGGER revisiones_imagenes_inmutables BEFORE UPDATE OR DELETE ON revisiones_imagenes "
        "FOR EACH ROW EXECUTE FUNCTION revisiones_imagenes_inmutables()"
    )
    for tabla in TABLAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS revisiones_imagenes_inmutables ON revisiones_imagenes")
    op.execute("DROP FUNCTION IF EXISTS revisiones_imagenes_inmutables()")
    op.execute("UPDATE imagenes_parcela SET documento_natural_id = NULL, documento_infrarrojo_id = NULL")
    op.execute("DELETE FROM documentos WHERE entidad = 'imagen' OR tipo IN ('imagen_satelital', 'imagen_externa')")
    op.drop_constraint(op.f("ck_documentos_subido_por_si_no_sistema"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_subido_por_si_no_sistema"), "documentos", SISTEMA_ANTES)
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_ANTES})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_ANTES})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_decisiones_habilitacion_evidencia_revision_id_revisiones_imagenes'), 'decisiones_habilitacion', type_='foreignkey')
    op.drop_column('decisiones_habilitacion', 'evidencia_revision_id')
    op.drop_index('ix_revisiones_imagenes_parcela', table_name='revisiones_imagenes')
    op.drop_table('revisiones_imagenes')
    op.drop_index('ix_imagenes_parcela_parcela', table_name='imagenes_parcela')
    op.drop_index('ix_imagenes_parcela_cola', table_name='imagenes_parcela')
    op.drop_table('imagenes_parcela')
    op.drop_index('ix_consumo_imagenes_mes', table_name='consumo_imagenes')
    op.drop_table('consumo_imagenes')
    # ### end Alembic commands ###
