"""Parte 6: calidades, plantilla de proceso, corridas con sus tandas y etapas, tandas finales y DPP

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-06

Regla: toda tabla nueva lleva ALTER TABLE <tabla> ENABLE ROW LEVEL SECURITY y ninguna política.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0009'
down_revision: str | Sequence[str] | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLAS = (
    "calidades",
    "plantilla_proceso",
    "corridas",
    "corrida_tandas",
    "corrida_etapas",
    "tandas_finales",
    "dpps",
)
CORRELATIVOS_ANTES = "'tanda', 'dop'"
CORRELATIVOS_AHORA = CORRELATIVOS_ANTES + ", 'corrida', 'tanda_final', 'dpp'"
ENTIDADES_ANTES = "'productor', 'parcela', 'visita', 'analisis', 'tanda', 'dop', 'imagen'"
ENTIDADES_AHORA = ENTIDADES_ANTES + ", 'dpp'"
TIPOS_ANTES = (
    "'dni', 'constancia_ppa', 'sustento_midagri', 'archivo_geometria', 'titulo_sunarp', 'constancia_posesion', "
    "'cusaf', 'autorizacion_serfor', 'sunafil', 'sunat', 'zonificacion', 'foto_visita', 'respuesta_analisis', "
    "'documento_entrega', 'dop_pdf', 'imagen_satelital', 'imagen_externa'"
)
TIPOS_AHORA = TIPOS_ANTES + ", 'dpp_pdf'"

# El DPP, como el DOP: el sello no cambia y no se borra; solo se anula.
FUNCION_DPPS = """
CREATE FUNCTION dpps_sellados() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Un DPP no se borra: se anula';
    END IF;
    IF NEW.contenido IS DISTINCT FROM OLD.contenido
       OR NEW.contenido_sha256 IS DISTINCT FROM OLD.contenido_sha256
       OR NEW.codigo IS DISTINCT FROM OLD.codigo
       OR NEW.corrida_id IS DISTINCT FROM OLD.corrida_id
       OR NEW.tanda_final_id IS DISTINCT FROM OLD.tanda_final_id THEN
        RAISE EXCEPTION 'El contenido sellado de un DPP no cambia';
    END IF;
    RETURN NEW;
END;
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_calidades_cooperativa_id_cooperativas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calidades')),
    sa.UniqueConstraint('cooperativa_id', 'nombre', name='uq_calidades_cooperativa_nombre')
    )
    op.create_table('corridas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('ruta', sa.Text(), nullable=False),
    sa.Column('tipo_manejo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), server_default='abierta', nullable=False),
    sa.Column('abierta_por', sa.UUID(), nullable=False),
    sa.Column('abierta_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consolidada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_por', sa.UUID(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(estado = 'anulada') = (anulada_en IS NOT NULL AND motivo_anulacion IS NOT NULL)", name=op.f('ck_corridas_anulacion_completa')),
    sa.CheckConstraint("estado IN ('abierta', 'en_proceso', 'consolidada', 'anulada')", name=op.f('ck_corridas_estado_valido')),
    sa.CheckConstraint("ruta IN ('completa', 'seco')", name=op.f('ck_corridas_ruta_valida')),
    sa.CheckConstraint("tipo_manejo IN ('segregado', 'mezclado')", name=op.f('ck_corridas_tipo_manejo_valido')),
    sa.ForeignKeyConstraint(['abierta_por'], ['perfiles.id'], name=op.f('fk_corridas_abierta_por_perfiles')),
    sa.ForeignKeyConstraint(['anulada_por'], ['perfiles.id'], name=op.f('fk_corridas_anulada_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_corridas_cooperativa_id_cooperativas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corridas')),
    sa.UniqueConstraint('cooperativa_id', 'codigo', name='uq_corridas_cooperativa_codigo')
    )
    op.create_index('ix_corridas_cooperativa_estado', 'corridas', ['cooperativa_id', 'estado'], unique=False)
    op.create_table('plantilla_proceso',
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('lugar_id', sa.UUID(), nullable=True),
    sa.Column('metodo', sa.Text(), nullable=True),
    sa.Column('distancia_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('duracion_horas', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('distancia_m IS NULL OR distancia_m >= 0', name=op.f('ck_plantilla_proceso_distancia_no_negativa')),
    sa.CheckConstraint('duracion_horas IS NULL OR duracion_horas >= 0', name=op.f('ck_plantilla_proceso_duracion_no_negativa')),
    sa.CheckConstraint('numero BETWEEN 1 AND 23', name=op.f('ck_plantilla_proceso_numero_valido')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_plantilla_proceso_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugares.id'], name=op.f('fk_plantilla_proceso_lugar_id_lugares')),
    sa.PrimaryKeyConstraint('cooperativa_id', 'numero', name=op.f('pk_plantilla_proceso'))
    )
    op.create_table('corrida_etapas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('corrida_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('situacion', sa.Text(), server_default='pendiente', nullable=False),
    sa.Column('lugar_id', sa.UUID(), nullable=True),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metodo', sa.Text(), nullable=True),
    sa.Column('responsable', sa.Text(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('distancia_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('desde_plantilla', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('registrada_por', sa.UUID(), nullable=True),
    sa.Column('registrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("situacion IN ('pendiente', 'registrada', 'no_aplica', 'no_ocurrio')", name=op.f('ck_corrida_etapas_situacion_valida')),
    sa.CheckConstraint('distancia_m IS NULL OR distancia_m >= 0', name=op.f('ck_corrida_etapas_distancia_no_negativa')),
    sa.CheckConstraint('fin IS NULL OR inicio IS NULL OR fin >= inicio', name=op.f('ck_corrida_etapas_fin_despues_de_inicio')),
    sa.CheckConstraint('numero BETWEEN 1 AND 23', name=op.f('ck_corrida_etapas_numero_valido')),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas.id'], name=op.f('fk_corrida_etapas_corrida_id_corridas')),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugares.id'], name=op.f('fk_corrida_etapas_lugar_id_lugares')),
    sa.ForeignKeyConstraint(['registrada_por'], ['perfiles.id'], name=op.f('fk_corrida_etapas_registrada_por_perfiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrida_etapas')),
    sa.UniqueConstraint('corrida_id', 'numero', name='uq_corrida_etapas_corrida_numero')
    )
    op.create_table('tandas_finales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('corrida_id', sa.UUID(), nullable=False),
    sa.Column('peso_seco_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('humedad_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('calidad', sa.Text(), nullable=False),
    sa.Column('calidad_id', sa.UUID(), nullable=False),
    sa.Column('numero_sacos', sa.Integer(), nullable=False),
    sa.Column('lugar_id', sa.UUID(), nullable=False),
    sa.Column('ingreso_stock_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Text(), server_default='en_stock', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('en_stock', 'agotada', 'anulada')", name=op.f('ck_tandas_finales_estado_valido')),
    sa.CheckConstraint('humedad_pct IS NULL OR humedad_pct BETWEEN 0 AND 100', name=op.f('ck_tandas_finales_humedad_valida')),
    sa.CheckConstraint('numero_sacos > 0', name=op.f('ck_tandas_finales_sacos_positivos')),
    sa.CheckConstraint('peso_seco_kg > 0', name=op.f('ck_tandas_finales_peso_positivo')),
    sa.CheckConstraint('saldo_kg >= 0 AND saldo_kg <= peso_seco_kg', name=op.f('ck_tandas_finales_saldo_valido')),
    sa.ForeignKeyConstraint(['calidad_id'], ['calidades.id'], name=op.f('fk_tandas_finales_calidad_id_calidades')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_tandas_finales_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas.id'], name=op.f('fk_tandas_finales_corrida_id_corridas')),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugares.id'], name=op.f('fk_tandas_finales_lugar_id_lugares')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tandas_finales')),
    sa.UniqueConstraint('cooperativa_id', 'codigo', name='uq_tandas_finales_cooperativa_codigo')
    )
    op.create_index('uq_tandas_finales_corrida_vigente', 'tandas_finales', ['corrida_id'], unique=True, postgresql_where=sa.text("estado <> 'anulada'"))
    op.create_table('dpps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('corrida_id', sa.UUID(), nullable=False),
    sa.Column('tanda_final_id', sa.UUID(), nullable=False),
    sa.Column('emitido_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emitido_por', sa.UUID(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contenido_sha256', sa.String(length=64), nullable=False),
    sa.Column('pdf_documento_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Text(), server_default='vigente', nullable=False),
    sa.Column('anulado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_por', sa.UUID(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.CheckConstraint("(estado = 'anulado') = (anulado_en IS NOT NULL AND anulado_por IS NOT NULL AND motivo_anulacion IS NOT NULL)", name=op.f('ck_dpps_anulacion_completa')),
    sa.CheckConstraint("contenido_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_dpps_sha256_hex')),
    sa.CheckConstraint("estado IN ('vigente', 'anulado')", name=op.f('ck_dpps_estado_valido')),
    sa.ForeignKeyConstraint(['anulado_por'], ['perfiles.id'], name=op.f('fk_dpps_anulado_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_dpps_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas.id'], name=op.f('fk_dpps_corrida_id_corridas')),
    sa.ForeignKeyConstraint(['emitido_por'], ['perfiles.id'], name=op.f('fk_dpps_emitido_por_perfiles')),
    sa.ForeignKeyConstraint(['pdf_documento_id'], ['documentos.id'], name=op.f('fk_dpps_pdf_documento_id_documentos')),
    sa.ForeignKeyConstraint(['tanda_final_id'], ['tandas_finales.id'], name=op.f('fk_dpps_tanda_final_id_tandas_finales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dpps')),
    sa.UniqueConstraint('codigo', name=op.f('uq_dpps_codigo')),
    sa.UniqueConstraint('tanda_final_id', name=op.f('uq_dpps_tanda_final_id'))
    )
    op.create_index('ix_dpps_cooperativa_emitido', 'dpps', ['cooperativa_id', 'emitido_en'], unique=False)
    op.create_table('corrida_tandas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('corrida_id', sa.UUID(), nullable=False),
    sa.Column('tanda_id', sa.UUID(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacion_calidad', sa.Text(), nullable=True),
    sa.Column('proporcion', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('agregada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('liberada_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('peso_kg > 0', name=op.f('ck_corrida_tandas_peso_positivo')),
    sa.CheckConstraint('proporcion IS NULL OR (proporcion > 0 AND proporcion <= 1)', name=op.f('ck_corrida_tandas_proporcion_valida')),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas.id'], name=op.f('fk_corrida_tandas_corrida_id_corridas')),
    sa.ForeignKeyConstraint(['tanda_id'], ['tandas.id'], name=op.f('fk_corrida_tandas_tanda_id_tandas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrida_tandas'))
    )
    op.create_index('ix_corrida_tandas_corrida', 'corrida_tandas', ['corrida_id'], unique=False)
    op.create_index('uq_corrida_tandas_tanda_activa', 'corrida_tandas', ['tanda_id'], unique=True, postgresql_where=sa.text('liberada_en IS NULL'))
    # ### end Alembic commands ###

    op.drop_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", type_="check")
    op.create_check_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", f"tipo IN ({CORRELATIVOS_AHORA})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_AHORA})")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_AHORA})")
    op.execute(FUNCION_DPPS)
    op.execute(
        "CREATE TRIGGER tg_dpps_sellados BEFORE UPDATE OR DELETE ON dpps "
        "FOR EACH ROW EXECUTE FUNCTION dpps_sellados()"
    )
    for tabla in TABLAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS tg_dpps_sellados ON dpps")
    op.execute("DROP FUNCTION IF EXISTS dpps_sellados()")
    op.execute("DELETE FROM documentos WHERE tipo = 'dpp_pdf'")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_ANTES})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_ANTES})")
    op.execute("DELETE FROM correlativos WHERE tipo IN ('corrida', 'tanda_final', 'dpp')")
    op.drop_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", type_="check")
    op.create_check_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", f"tipo IN ({CORRELATIVOS_ANTES})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_corrida_tandas_tanda_activa', table_name='corrida_tandas', postgresql_where=sa.text('liberada_en IS NULL'))
    op.drop_index('ix_corrida_tandas_corrida', table_name='corrida_tandas')
    op.drop_table('corrida_tandas')
    op.drop_index('ix_dpps_cooperativa_emitido', table_name='dpps')
    op.drop_table('dpps')
    op.drop_index('uq_tandas_finales_corrida_vigente', table_name='tandas_finales', postgresql_where=sa.text("estado <> 'anulada'"))
    op.drop_table('tandas_finales')
    op.drop_table('corrida_etapas')
    op.drop_table('plantilla_proceso')
    op.drop_index('ix_corridas_cooperativa_estado', table_name='corridas')
    op.drop_table('corridas')
    op.drop_table('calidades')
    # ### end Alembic commands ###
