"""Parte 7: importadores, órdenes de compra, lotes de exportación y genealogía

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-06

Regla: toda tabla nueva lleva ALTER TABLE <tabla> ENABLE ROW LEVEL SECURITY y ninguna política.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0010"
down_revision: str | Sequence[str] | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLAS = ("importadores", "ordenes_compra", "lotes", "lote_asignaciones", "lote_genealogia")
CORRELATIVOS_ANTES = "'tanda', 'dop', 'corrida', 'tanda_final', 'dpp'"
CORRELATIVOS_AHORA = CORRELATIVOS_ANTES + ", 'orden', 'lote'"

# La genealogía del lote no se edita ni se borra: si el lote se anula, queda como historial.
FUNCION_GENEALOGIA = """
CREATE FUNCTION lote_genealogia_fija() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'La genealogía de un lote no se edita ni se borra';
END;
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "importadores",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cooperativa_id", sa.UUID(), nullable=False),
        sa.Column("razon_social", sa.Text(), nullable=False),
        sa.Column("direccion", sa.Text(), nullable=False),
        sa.Column("pais", sa.Text(), nullable=False),
        sa.Column("correo", sa.Text(), nullable=False),
        sa.Column("eori", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "actualizado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cooperativa_id"], ["cooperativas.id"], name=op.f("fk_importadores_cooperativa_id_cooperativas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_importadores")),
    )
    op.create_index("ix_importadores_cooperativa", "importadores", ["cooperativa_id"], unique=False)
    op.create_table(
        "ordenes_compra",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cooperativa_id", sa.UUID(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("importador_id", sa.UUID(), nullable=False),
        sa.Column("referencia_importador", sa.Text(), nullable=True),
        sa.Column("cantidad_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "tolerancia_pct", sa.Numeric(precision=4, scale=1), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("calidad_id", sa.UUID(), nullable=False),
        sa.Column("partida_sa", sa.Text(), server_default="1801", nullable=False),
        sa.Column("pais_destino", sa.Text(), nullable=False),
        sa.Column("lugar_destino", sa.Text(), nullable=False),
        sa.Column("fecha_entrega", sa.Date(), nullable=False),
        sa.Column("estado", sa.Text(), server_default="abierta", nullable=False),
        sa.Column("creada_por", sa.UUID(), nullable=False),
        sa.Column("anulada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anulada_por", sa.UUID(), nullable=True),
        sa.Column("motivo_anulacion", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "actualizado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(estado = 'anulada') = (anulada_en IS NOT NULL AND motivo_anulacion IS NOT NULL)",
            name=op.f("ck_ordenes_compra_anulacion_completa"),
        ),
        sa.CheckConstraint(
            "estado IN ('abierta', 'con_lote', 'cerrada', 'anulada')",
            name=op.f("ck_ordenes_compra_estado_valido"),
        ),
        sa.CheckConstraint("partida_sa = '1801'", name=op.f("ck_ordenes_compra_partida_cacao_en_grano")),
        sa.CheckConstraint("cantidad_kg > 0", name=op.f("ck_ordenes_compra_cantidad_positiva")),
        sa.CheckConstraint(
            "tolerancia_pct >= 0 AND tolerancia_pct <= 100", name=op.f("ck_ordenes_compra_tolerancia_valida")
        ),
        sa.ForeignKeyConstraint(
            ["anulada_por"], ["perfiles.id"], name=op.f("fk_ordenes_compra_anulada_por_perfiles")
        ),
        sa.ForeignKeyConstraint(
            ["calidad_id"], ["calidades.id"], name=op.f("fk_ordenes_compra_calidad_id_calidades")
        ),
        sa.ForeignKeyConstraint(
            ["cooperativa_id"],
            ["cooperativas.id"],
            name=op.f("fk_ordenes_compra_cooperativa_id_cooperativas"),
        ),
        sa.ForeignKeyConstraint(
            ["creada_por"], ["perfiles.id"], name=op.f("fk_ordenes_compra_creada_por_perfiles")
        ),
        sa.ForeignKeyConstraint(
            ["importador_id"], ["importadores.id"], name=op.f("fk_ordenes_compra_importador_id_importadores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ordenes_compra")),
        sa.UniqueConstraint("cooperativa_id", "codigo", name="uq_ordenes_compra_codigo"),
    )
    op.create_index(
        "ix_ordenes_compra_cooperativa_estado", "ordenes_compra", ["cooperativa_id", "estado"], unique=False
    )
    op.create_table(
        "lotes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cooperativa_id", sa.UUID(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("orden_compra_id", sa.UUID(), nullable=False),
        sa.Column("estado", sa.Text(), server_default="en_armado", nullable=False),
        sa.Column("masa_neta_kg", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("desviacion_fifo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("motivo_desviacion", sa.Text(), nullable=True),
        sa.Column("creado_por", sa.UUID(), nullable=False),
        sa.Column("armado_por", sa.UUID(), nullable=True),
        sa.Column("armado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anulado_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anulado_por", sa.UUID(), nullable=True),
        sa.Column("motivo_anulacion", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "actualizado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(estado = 'anulado') = (anulado_en IS NOT NULL AND motivo_anulacion IS NOT NULL)",
            name=op.f("ck_lotes_anulacion_completa"),
        ),
        sa.CheckConstraint(
            "estado = 'en_armado' OR anulado_en IS NOT NULL OR (masa_neta_kg IS NOT NULL AND armado_en IS NOT NULL)",
            name=op.f("ck_lotes_armado_completo"),
        ),
        sa.CheckConstraint(
            "estado IN ('en_armado', 'armado', 'anulado')", name=op.f("ck_lotes_estado_valido")
        ),
        sa.CheckConstraint(
            "NOT desviacion_fifo OR char_length(motivo_desviacion) >= 30",
            name=op.f("ck_lotes_motivo_de_la_desviacion"),
        ),
        sa.CheckConstraint("masa_neta_kg IS NULL OR masa_neta_kg > 0", name=op.f("ck_lotes_masa_positiva")),
        sa.ForeignKeyConstraint(["anulado_por"], ["perfiles.id"], name=op.f("fk_lotes_anulado_por_perfiles")),
        sa.ForeignKeyConstraint(["armado_por"], ["perfiles.id"], name=op.f("fk_lotes_armado_por_perfiles")),
        sa.ForeignKeyConstraint(
            ["cooperativa_id"], ["cooperativas.id"], name=op.f("fk_lotes_cooperativa_id_cooperativas")
        ),
        sa.ForeignKeyConstraint(["creado_por"], ["perfiles.id"], name=op.f("fk_lotes_creado_por_perfiles")),
        sa.ForeignKeyConstraint(
            ["orden_compra_id"], ["ordenes_compra.id"], name=op.f("fk_lotes_orden_compra_id_ordenes_compra")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lotes")),
        sa.UniqueConstraint("cooperativa_id", "codigo", name="uq_lotes_codigo"),
    )
    op.create_index("ix_lotes_cooperativa_estado", "lotes", ["cooperativa_id", "estado"], unique=False)
    op.create_index(
        "uq_lotes_orden_vigente",
        "lotes",
        ["orden_compra_id"],
        unique=True,
        postgresql_where=sa.text("estado <> 'anulado'"),
    )
    op.create_table(
        "lote_asignaciones",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lote_id", sa.UUID(), nullable=False),
        sa.Column("tanda_final_id", sa.UUID(), nullable=False),
        sa.Column("kg_asignados", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint("kg_asignados > 0", name=op.f("ck_lote_asignaciones_kg_positivos")),
        sa.ForeignKeyConstraint(["lote_id"], ["lotes.id"], name=op.f("fk_lote_asignaciones_lote_id_lotes")),
        sa.ForeignKeyConstraint(
            ["tanda_final_id"],
            ["tandas_finales.id"],
            name=op.f("fk_lote_asignaciones_tanda_final_id_tandas_finales"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lote_asignaciones")),
        sa.UniqueConstraint("lote_id", "tanda_final_id", name="uq_lote_asignaciones_tanda_final"),
    )
    op.create_index("ix_lote_asignaciones_tanda_final", "lote_asignaciones", ["tanda_final_id"], unique=False)
    op.create_table(
        "lote_genealogia",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lote_id", sa.UUID(), nullable=False),
        sa.Column("tanda_final_id", sa.UUID(), nullable=False),
        sa.Column("dpp_id", sa.UUID(), nullable=False),
        sa.Column("tanda_id", sa.UUID(), nullable=False),
        sa.Column("dop_id", sa.UUID(), nullable=False),
        sa.Column("parcela_id", sa.UUID(), nullable=False),
        sa.Column("productor_id", sa.UUID(), nullable=False),
        sa.Column("kg_atribuidos", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("proporcion_lote", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kg_atribuidos >= 0", name=op.f("ck_lote_genealogia_kg_no_negativos")),
        sa.CheckConstraint(
            "proporcion_lote >= 0 AND proporcion_lote <= 1", name=op.f("ck_lote_genealogia_proporcion_valida")
        ),
        sa.ForeignKeyConstraint(["dop_id"], ["dops.id"], name=op.f("fk_lote_genealogia_dop_id_dops")),
        sa.ForeignKeyConstraint(["dpp_id"], ["dpps.id"], name=op.f("fk_lote_genealogia_dpp_id_dpps")),
        sa.ForeignKeyConstraint(["lote_id"], ["lotes.id"], name=op.f("fk_lote_genealogia_lote_id_lotes")),
        sa.ForeignKeyConstraint(
            ["parcela_id"], ["parcelas.id"], name=op.f("fk_lote_genealogia_parcela_id_parcelas")
        ),
        sa.ForeignKeyConstraint(
            ["productor_id"], ["productores.id"], name=op.f("fk_lote_genealogia_productor_id_productores")
        ),
        sa.ForeignKeyConstraint(
            ["tanda_final_id"],
            ["tandas_finales.id"],
            name=op.f("fk_lote_genealogia_tanda_final_id_tandas_finales"),
        ),
        sa.ForeignKeyConstraint(["tanda_id"], ["tandas.id"], name=op.f("fk_lote_genealogia_tanda_id_tandas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lote_genealogia")),
    )
    op.create_index("ix_lote_genealogia_lote", "lote_genealogia", ["lote_id"], unique=False)
    op.create_index("ix_lote_genealogia_parcela", "lote_genealogia", ["parcela_id"], unique=False)
    op.create_index("ix_lote_genealogia_tanda", "lote_genealogia", ["tanda_id"], unique=False)
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", type_="check")
    op.create_check_constraint(
        op.f("ck_correlativos_tipo_valido"), "correlativos", f"tipo IN ({CORRELATIVOS_AHORA})"
    )
    op.execute(FUNCION_GENEALOGIA)
    op.execute(
        "CREATE TRIGGER tg_lote_genealogia_fija BEFORE UPDATE OR DELETE ON lote_genealogia "
        "FOR EACH ROW EXECUTE FUNCTION lote_genealogia_fija()"
    )
    for tabla in TABLAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS tg_lote_genealogia_fija ON lote_genealogia")
    op.execute("DROP FUNCTION IF EXISTS lote_genealogia_fija()")
    op.execute("DELETE FROM correlativos WHERE tipo IN ('orden', 'lote')")
    op.drop_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", type_="check")
    op.create_check_constraint(
        op.f("ck_correlativos_tipo_valido"), "correlativos", f"tipo IN ({CORRELATIVOS_ANTES})"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lote_genealogia_tanda", table_name="lote_genealogia")
    op.drop_index("ix_lote_genealogia_parcela", table_name="lote_genealogia")
    op.drop_index("ix_lote_genealogia_lote", table_name="lote_genealogia")
    op.drop_table("lote_genealogia")
    op.drop_index("ix_lote_asignaciones_tanda_final", table_name="lote_asignaciones")
    op.drop_table("lote_asignaciones")
    op.drop_index(
        "uq_lotes_orden_vigente", table_name="lotes", postgresql_where=sa.text("estado <> 'anulado'")
    )
    op.drop_index("ix_lotes_cooperativa_estado", table_name="lotes")
    op.drop_table("lotes")
    op.drop_index("ix_ordenes_compra_cooperativa_estado", table_name="ordenes_compra")
    op.drop_table("ordenes_compra")
    op.drop_index("ix_importadores_cooperativa", table_name="importadores")
    op.drop_table("importadores")
    # ### end Alembic commands ###
