"""Parte 8: datos y expediente legal de la cooperativa, documentos de embarque, recomprobación del lote

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-06

Regla: toda tabla nueva lleva ALTER TABLE <tabla> ENABLE ROW LEVEL SECURITY y ninguna política.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0011'
down_revision: str | Sequence[str] | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENTIDADES_ANTES = "'productor', 'parcela', 'visita', 'analisis', 'tanda', 'dop', 'imagen', 'dpp'"
ENTIDADES_AHORA = ENTIDADES_ANTES + ", 'cooperativa', 'lote'"
TIPOS_ANTES = (
    "'dni', 'constancia_ppa', 'sustento_midagri', 'archivo_geometria', 'titulo_sunarp', 'constancia_posesion', "
    "'cusaf', 'autorizacion_serfor', 'sunafil', 'sunat', 'zonificacion', 'foto_visita', 'respuesta_analisis', "
    "'documento_entrega', 'dop_pdf', 'dpp_pdf', 'imagen_satelital', 'imagen_externa'"
)
TIPOS_AHORA = TIPOS_ANTES + (
    ", 'rnca', 'partida_sunarp', 'ficha_ruc', 'vigencia_poderes', 'ruc_comercio_exterior', 'registro_aduanas', "
    "'factura_comercial', 'packing_list', 'certificado_origen', 'certificado_fitosanitario'"
)
LOTE_ANTES = "'en_armado', 'armado', 'anulado'"
LOTE_AHORA = "'en_armado', 'armado', 'bloqueado', 'listo', 'cerrado', 'anulado'"

# La recomprobación queda como historial: no se edita ni se borra.
FUNCION_RECOMPROBACIONES = """
CREATE FUNCTION recomprobaciones_fijas() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Una recomprobación no se edita ni se borra';
END;
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomprobaciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('ejecutada_por', sa.UUID(), nullable=True),
    sa.Column('ejecutada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("resultado IN ('sin_observaciones', 'con_observaciones')", name=op.f('ck_recomprobaciones_resultado_valido')),
    sa.ForeignKeyConstraint(['ejecutada_por'], ['perfiles.id'], name=op.f('fk_recomprobaciones_ejecutada_por_perfiles')),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_recomprobaciones_lote_id_lotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recomprobaciones'))
    )
    op.create_index('ix_recomprobaciones_lote_ejecutada', 'recomprobaciones', ['lote_id', 'ejecutada_en'], unique=False)
    op.add_column('cooperativas', sa.Column('direccion_postal', sa.Text(), nullable=True))
    op.add_column('cooperativas', sa.Column('correo', sa.Text(), nullable=True))
    op.add_column('cooperativas', sa.Column('representante_nombre', sa.Text(), nullable=True))
    op.add_column('cooperativas', sa.Column('representante_dni', sa.String(length=8), nullable=True))
    op.add_column('lotes', sa.Column('alertas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_cooperativas_representante_dni_8_digitos"),
        "cooperativas",
        "representante_dni IS NULL OR representante_dni ~ '^[0-9]{8}$'",
    )
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_AHORA})")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_AHORA})")
    op.drop_constraint(op.f("ck_lotes_estado_valido"), "lotes", type_="check")
    op.create_check_constraint(op.f("ck_lotes_estado_valido"), "lotes", f"estado IN ({LOTE_AHORA})")
    op.execute(FUNCION_RECOMPROBACIONES)
    op.execute(
        "CREATE TRIGGER tg_recomprobaciones_fijas BEFORE UPDATE OR DELETE ON recomprobaciones "
        "FOR EACH ROW EXECUTE FUNCTION recomprobaciones_fijas()"
    )
    op.execute("ALTER TABLE recomprobaciones ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS tg_recomprobaciones_fijas ON recomprobaciones")
    op.execute("DROP FUNCTION IF EXISTS recomprobaciones_fijas()")
    op.execute("UPDATE lotes SET estado = 'armado' WHERE estado IN ('bloqueado', 'listo', 'cerrado')")
    op.drop_constraint(op.f("ck_lotes_estado_valido"), "lotes", type_="check")
    op.create_check_constraint(op.f("ck_lotes_estado_valido"), "lotes", f"estado IN ({LOTE_ANTES})")
    op.execute("DELETE FROM documentos WHERE entidad IN ('cooperativa', 'lote')")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_ANTES})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_ANTES})")
    op.drop_constraint(op.f("ck_cooperativas_representante_dni_8_digitos"), "cooperativas", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes', 'alertas')
    op.drop_column('cooperativas', 'representante_dni')
    op.drop_column('cooperativas', 'representante_nombre')
    op.drop_column('cooperativas', 'correo')
    op.drop_column('cooperativas', 'direccion_postal')
    op.drop_index('ix_recomprobaciones_lote_ejecutada', table_name='recomprobaciones')
    op.drop_table('recomprobaciones')
    # ### end Alembic commands ###
