"""Parte 9: DEX sellado, certificaciones de la cooperativa y configuración de plataforma

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-06

Regla: toda tabla nueva lleva ALTER TABLE <tabla> ENABLE ROW LEVEL SECURITY y ninguna política.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0012'
down_revision: str | Sequence[str] | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLAS = ("dex", "certificaciones", "configuracion_plataforma")
CORRELATIVOS_ANTES = "'tanda', 'dop', 'corrida', 'tanda_final', 'dpp', 'orden', 'lote'"
CORRELATIVOS_AHORA = CORRELATIVOS_ANTES + ", 'dex'"
ENTIDADES_ANTES = "'productor', 'parcela', 'visita', 'analisis', 'tanda', 'dop', 'imagen', 'dpp', 'cooperativa', 'lote'"
ENTIDADES_AHORA = ENTIDADES_ANTES + ", 'certificacion', 'dex'"
TIPOS_ANTES = (
    "'dni', 'constancia_ppa', 'sustento_midagri', 'archivo_geometria', 'titulo_sunarp', 'constancia_posesion', "
    "'cusaf', 'autorizacion_serfor', 'sunafil', 'sunat', 'zonificacion', 'foto_visita', 'respuesta_analisis', "
    "'documento_entrega', 'dop_pdf', 'dpp_pdf', 'imagen_satelital', 'imagen_externa', 'rnca', 'partida_sunarp', "
    "'ficha_ruc', 'vigencia_poderes', 'ruc_comercio_exterior', 'registro_aduanas', 'factura_comercial', "
    "'packing_list', 'certificado_origen', 'certificado_fitosanitario'"
)
TIPOS_AHORA = TIPOS_ANTES + (
    ", 'certificacion', 'dex_pdf_es', 'dex_pdf_en', 'dex_geojson', 'dex_anexo_ii', 'dex_hallazgos', "
    "'dex_leeme', 'dex_paquete'"
)

# El DEX, como el DOP y el DPP: el sello no cambia y no se borra; solo se anula.
FUNCION_DEX = """
CREATE FUNCTION dex_sellados() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Un DEX no se borra: se anula';
    END IF;
    IF NEW.contenido IS DISTINCT FROM OLD.contenido
       OR NEW.contenido_sha256 IS DISTINCT FROM OLD.contenido_sha256
       OR NEW.codigo IS DISTINCT FROM OLD.codigo
       OR NEW.lote_id IS DISTINCT FROM OLD.lote_id THEN
        RAISE EXCEPTION 'El contenido sellado de un DEX no cambia';
    END IF;
    RETURN NEW;
END;
$$
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_plataforma',
    sa.Column('id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('clasificacion_pais', sa.Text(), nullable=True),
    sa.Column('clasificacion_fecha', sa.Date(), nullable=True),
    sa.Column('clasificacion_referencia', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("clasificacion_pais IS NULL OR clasificacion_pais IN ('bajo', 'estandar', 'alto')", name=op.f('ck_configuracion_plataforma_clasificacion_valida')),
    sa.CheckConstraint('id = 1', name=op.f('ck_configuracion_plataforma_una_sola_fila')),
    sa.ForeignKeyConstraint(['actualizado_por'], ['perfiles.id'], name=op.f('fk_configuracion_plataforma_actualizado_por_perfiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracion_plataforma'))
    )
    op.create_table('certificaciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('entidad_certificadora', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('registrada_por', sa.UUID(), nullable=False),
    sa.Column('anulada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_por', sa.UUID(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(anulada_en IS NULL) = (motivo_anulacion IS NULL)', name=op.f('ck_certificaciones_anulacion_completa')),
    sa.CheckConstraint('vigente_hasta >= vigente_desde', name=op.f('ck_certificaciones_periodo_valido')),
    sa.ForeignKeyConstraint(['anulada_por'], ['perfiles.id'], name=op.f('fk_certificaciones_anulada_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_certificaciones_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_certificaciones_documento_id_documentos')),
    sa.ForeignKeyConstraint(['registrada_por'], ['perfiles.id'], name=op.f('fk_certificaciones_registrada_por_perfiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificaciones'))
    )
    op.create_index('ix_certificaciones_cooperativa', 'certificaciones', ['cooperativa_id'], unique=False)
    op.create_table('dex',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cooperativa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('emitido_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emitido_por', sa.UUID(), nullable=False),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contenido_sha256', sa.String(length=64), nullable=False),
    sa.Column('archivos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('estado', sa.Text(), server_default='vigente', nullable=False),
    sa.Column('anulado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_por', sa.UUID(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.CheckConstraint("(estado = 'anulado') = (anulado_en IS NOT NULL AND anulado_por IS NOT NULL AND motivo_anulacion IS NOT NULL)", name=op.f('ck_dex_anulacion_completa')),
    sa.CheckConstraint("contenido_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_dex_sha256_hex')),
    sa.CheckConstraint("estado IN ('vigente', 'anulado')", name=op.f('ck_dex_estado_valido')),
    sa.ForeignKeyConstraint(['anulado_por'], ['perfiles.id'], name=op.f('fk_dex_anulado_por_perfiles')),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], name=op.f('fk_dex_cooperativa_id_cooperativas')),
    sa.ForeignKeyConstraint(['emitido_por'], ['perfiles.id'], name=op.f('fk_dex_emitido_por_perfiles')),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_dex_lote_id_lotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dex')),
    sa.UniqueConstraint('codigo', name=op.f('uq_dex_codigo'))
    )
    op.create_index('ix_dex_cooperativa_emitido', 'dex', ['cooperativa_id', 'emitido_en'], unique=False)
    op.create_index('uq_dex_lote_vigente', 'dex', ['lote_id'], unique=True, postgresql_where=sa.text("estado <> 'anulado'"))
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", type_="check")
    op.create_check_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", f"tipo IN ({CORRELATIVOS_AHORA})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_AHORA})")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_AHORA})")
    op.execute(FUNCION_DEX)
    op.execute(
        "CREATE TRIGGER tg_dex_sellados BEFORE UPDATE OR DELETE ON dex "
        "FOR EACH ROW EXECUTE FUNCTION dex_sellados()"
    )
    for tabla in TABLAS:
        op.execute(f"ALTER TABLE {tabla} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS tg_dex_sellados ON dex")
    op.execute("DROP FUNCTION IF EXISTS dex_sellados()")
    op.execute("DELETE FROM documentos WHERE entidad IN ('certificacion', 'dex')")
    op.drop_constraint(op.f("ck_documentos_tipo_valido"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_tipo_valido"), "documentos", f"tipo IN ({TIPOS_ANTES})")
    op.drop_constraint(op.f("ck_documentos_entidad_valida"), "documentos", type_="check")
    op.create_check_constraint(op.f("ck_documentos_entidad_valida"), "documentos", f"entidad IN ({ENTIDADES_ANTES})")
    op.execute("DELETE FROM correlativos WHERE tipo = 'dex'")
    op.drop_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", type_="check")
    op.create_check_constraint(op.f("ck_correlativos_tipo_valido"), "correlativos", f"tipo IN ({CORRELATIVOS_ANTES})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_dex_lote_vigente', table_name='dex', postgresql_where=sa.text("estado <> 'anulado'"))
    op.drop_index('ix_dex_cooperativa_emitido', table_name='dex')
    op.drop_table('dex')
    op.drop_index('ix_certificaciones_cooperativa', table_name='certificaciones')
    op.drop_table('certificaciones')
    op.drop_table('configuracion_plataforma')
    # ### end Alembic commands ###
